<datalist id="job-titles">
     <option value="Accountant">
     <option value="Administrative Assistant">
     <option value="Architect">
     <option value="Sales Clerk">
     <option value="Waiter/Waitress">
     <option value="Cashier">
     <option value="Call Center Agent">
     <option value="Office Clerk">
     <option value="Retail Sales Associate">
     <option value="Data Entry Operator">
     <option value="Security Guard">
     <option value="Delivery Driver">
     <option value="Receptionist">
     <option value="Housekeeper">
     <option value="Warehouse Worker">
     <option value="Janitor">
     <option value="Production Operator">
     <option value="Farm Laborer">
     <option value="Cook">
     <option value="Garbage Collector">
     <option value="Laundry Worker">
     <option value="Construction Laborer">
     <option value="Factory Worker">
     <option value="Gardener">
     <option value="Food Server">
     <option value="Caregiver">
     <option value="Street Sweeper">
     <option value="Pet Groomer">
     <option value="Messenger">
     <option value="Valet Parking Attendant">
     <option value="Babysitter">
     <option value="Painter">
     <option value="Farmhand">
     <option value="Dishwasher">
     <option value="Gasoline Attendant">
     <option value="Groundskeeper">
     <option value="Porter">
     <option value="Bar Helper">
     <option value="House Painter">
     <option value="Nanny">
     <option value="Parking Lot Attendant">
     <option value="Messenger">
     <option value="Bus Conductor">
     <option value="Dishwasher">
     <option value="Retail Merchandiser">
     <option value="Grocery Bagger">
     <option value="Day Laborer">
     <option value="Fruit Picker">
     <option value="Utility Worker">
     <option value="Car Washer">
     <option value="Gas Station Attendant">
     <option value="Messenger">
     <option value="Restaurant Server">
     <option value="Bank Teller">
     <option value="Barista">
     <option value="Bartender">
     <option value="Business Analyst">
     <option value="Cashier">
     <option value="Civil Engineer">
     <option value="Content Writer">
     <option value="Customer Service Representative">
     <option value="Data Analyst">
     <option value="Digital Marketing Specialist">
     <option value="Electrical Engineer">
     <option value="Graphic Designer">
     <option value="Human Resources Manager">
     <option value="IT Support Specialist">
     <option value="Java Developer">
     <option value="Legal Assistant">
     <option value="Marketing Manager">
     <option value="Medical Technologist">
     <option value="Nurse">
     <option value="Office Manager">
     <option value="Operations Manager">
     <option value="Pharmacist">
     <option value="Photographer">
     <option value="Product Manager">
     <option value="Project Manager">
     <option value="Receptionist">
     <option value="Registered Nurse">
     <option value="Sales Representative">
     <option value="Software Engineer">
     <option value="Teacher">
     <option value="Web Developer">
     <option value="Account Manager">
     <option value="Chef">
     <option value="Computer Programmer">
     <option value="Data Entry Clerk">
     <option value="Financial Analyst">
     <option value="Hotel Manager">
     <option value="Java Developer">
     <option value="Marketing Coordinator">
     <option value="Operations Coordinator">
     <option value="Physical Therapist">
     <option value="Product Manager">
     <option value="Public Relations Specialist">
     <option value="Sales Manager">
     <option value="Software Developer">
     <option value="Technical Support Specialist">
     <option value="Waiter/Waitress">
</datalist>

<datalist id="skill-list">
     <option value="Effective Communication">
     <option value="Adaptability">
     <option value="Customer Service">
     <option value="Teamwork">
     <option value="Time Management">
     <option value="Attention to Detail">
     <option value="Problem-Solving">
     <option value="Leadership">
     <option value="Critical Thinking">
     <option value="Creativity">
     <option value="Emotional Intelligence">
     <option value="Interpersonal Skills">
     <option value="Conflict Resolution">
     <option value="Empathy">
     <option value="Stress Management">
     <option value="Decision-Making">
     <option value="Negotiation">
     <option value="Active Listening">
     <option value="Organizational Skills">
     <option value="Flexibility">
     <option value="Initiative">
     <option value="Motivation">
     <option value="Positivity">
     <option value="Resilience">
     <option value="Self-Motivation">
     <option value="Work Ethic">
     <option value="Integrity">
     <option value="Cultural Sensitivity">
     <option value="Diplomacy">
     <option value="Adaptation to Change">
     <option value="Patience">
     <option value="Collaboration">
     <option value="Customer Relationship Management">
     <option value="Multitasking">
     <option value="Networking">
     <option value="Open-Mindedness">
     <option value="Tolerance">
     <option value="Time Management">
     <option value="Prioritization">
     <option value="Goal Setting">
     <option value="Delegation">
     <option value="Accountability">
     <option value="Conflict Management">
     <option value="Coaching">
     <option value="Presentation Skills">
     <option value="Problem Identification">
     <option value="Learning Agility">
     <option value="Decision-Making">
     <option value="Team Building">
     <option value="Self-Discipline">
     <option value="Web Development">
     <option value="Software Development">
     <option value="IT Support">
     <option value="Graphic Design">
     <option value="Multimedia Production">
     <option value="Mobile App Development">
     <option value="Database Administration">
     <option value="Network Administration">
     <option value="Systems Analysis">
     <option value="Quality Assurance Testing">
     <option value="Digital Marketing">
     <option value="SEO (Search Engine Optimization)">
     <option value="Content Writing">
     <option value="Database Management">
     <option value="Data Analysis">
     <option value="Project Management">
     <option value="Cybersecurity">
     <option value="Network Security">
     <option value="Software Quality Assurance">
     <option value="Data Science">
     <option value="Mobile Game Development">
     <option value="E-commerce Management">
     <option value="Hardware Troubleshooting">
     <option value="Cloud Computing">
     <option value="Electrical Engineering">
     <option value="Mechanical Engineering">
     <option value="Industrial Automation">
     <option value="Accounting">
     <option value="Financial Analysis">
     <option value="Marketing Analytics">
     <option value="Java Programming">
     <option value="C# Programming">
     <option value="Python Programming">
     <option value="Front-End Development">
     <option value="Back-End Development">
     <option value="UI/UX Design">
     <option value="Artificial Intelligence (AI)">
     <option value="Machine Learning">
     <option value="Robotics">
     <option value="3D Modeling">
     <option value="Video Editing">
     <option value="Audio Production">
     <option value="Health Care Management">
     <option value="Nursing">
     <option value="Medical Technology">
     <option value="Telecommunications">
     <option value="Environmental Science">
     <option value="Geographical Information Systems (GIS)">
     <option value="Civil Engineering">
     <option value="AutoCAD Design">
</datalist>

<datalist id="degree-list">
     <option value="Associate Degree (AA/AS)">
     <option value="Bachelor's Degree (BA/BS)">
     <option value="Master's Degree (MA/MS)">
     <option value="Doctoral Degree (Ph.D./Ed.D.)">
     <option value="Doctor of Medicine (MD)">
     <option value="Doctor of Dental Medicine (DMD) or Doctor of Dental Surgery (DDS)">
     <option value="Doctor of Jurisprudence (JD)">
     <option value="Doctor of Pharmacy (Pharm.D.)">
     <option value="Doctor of Veterinary Medicine (DVM)">
     <option value="Honorary Degrees">
     <option value="Online Degrees">
     <option value="Certificate/Diploma">
     <option value="Professional Degrees">
     <option value="Specialized Degrees">
</datalist>

<datalist id="field-study-list">
     <option value="Business and Management">
     <option value="Engineering">
     <option value="Education">
     <option value="Nursing and Healthcare">
     <option value="Information Technology (IT)">
     <option value="Tourism and Hospitality">
     <option value="Accounting and Finance">
     <option value="Criminology and Law Enforcement">
     <option value="Mass Communication and Journalism">
     <option value="Architecture and Design">
     <option value="Medical and Health Sciences">
     <option value="Environmental Science">
     <option value="Social Sciences">
     <option value="Agriculture and Agribusiness">
     <option value="Marine Biology and Fisheries">
     <option value="Computer Science">
     <option value="Psychology">
     <option value="Political Science">
     <option value="Civil Engineering">
     <option value="Pharmacy">
     <option value="Communication Arts">
     <option value="Electrical Engineering">
     <option value="Culinary Arts">
     <option value="Dentistry">
     <option value="Fine Arts">
     <option value="Mechanical Engineering">
     <option value="Hospitality Management">
     <option value="Economics">
     <option value="Chemical Engineering">
     <option value="Information Systems">
     <option value="Physical Therapy">
     <option value="Mathematics">
     <option value="Geology">
     <option value="Human Resource Management">
     <option value="Industrial Engineering">
     <option value="Marketing">
     <option value="Geography">
     <option value="Public Administration">
     <option value="Biological Sciences">
     <option value="Biomedical Engineering">
     <option value="Information Security">
     <option value="Speech Pathology">
     <option value="Biotechnology">
     <option value="Chemistry">
     <option value="Environmental Engineering">
     <option value="Data Science">
     <option value="Social Work">
     <option value="Library and Information Science">
     <option value="Applied Statistics">
     <option value="Aviation and Aeronautics">
     <option value="Archaeology">
     <option value="Tourism Management">
</datalist>

<datalist id="field-study-list">
     <option value="Business and Management">
     <option value="Engineering">
     <option value="Education">
     <option value="Nursing and Healthcare">
     <option value="Information Technology (IT)">
     <option value="Tourism and Hospitality">
     <option value="Accounting and Finance">
     <option value="Criminology and Law Enforcement">
     <option value="Mass Communication and Journalism">
     <option value="Architecture and Design">
     <option value="Medical and Health Sciences">
     <option value="Environmental Science">
     <option value="Social Sciences">
     <option value="Agriculture and Agribusiness">
     <option value="Marine Biology and Fisheries">
     <option value="Computer Science">
     <option value="Psychology">
     <option value="Political Science">
     <option value="Civil Engineering">
     <option value="Pharmacy">
     <option value="Communication Arts">
     <option value="Electrical Engineering">
     <option value="Culinary Arts">
     <option value="Dentistry">
     <option value="Fine Arts">
     <option value="Mechanical Engineering">
     <option value="Hospitality Management">
     <option value="Economics">
     <option value="Chemical Engineering">
     <option value="Information Systems">
     <option value="Physical Therapy">
     <option value="Mathematics">
     <option value="Geology">
     <option value="Human Resource Management">
     <option value="Industrial Engineering">
     <option value="Marketing">
     <option value="Geography">
     <option value="Public Administration">
     <option value="Biological Sciences">
     <option value="Biomedical Engineering">
     <option value="Information Security">
     <option value="Speech Pathology">
     <option value="Biotechnology">
     <option value="Chemistry">
     <option value="Environmental Engineering">
     <option value="Data Science">
     <option value="Social Work">
     <option value="Library and Information Science">
     <option value="Applied Statistics">
     <option value="Aviation and Aeronautics">
     <option value="Archaeology">
     <option value="Tourism Management">
</datalist>