
<datalist id="job-titles">
     <option value="Accountant">
     <option value="Administrative Assistant">
     <option value="Architect">
     <option value="Sales Clerk">
     <option value="Waiter/Waitress">
     <option value="Cashier">
     <option value="Call Center Agent">
     <option value="Office Clerk">
     <option value="Retail Sales Associate">
     <option value="Data Entry Operator">
     <option value="Security Guard">
     <option value="Delivery Driver">
     <option value="Receptionist">
     <option value="Housekeeper">
     <option value="Warehouse Worker">
     <option value="Janitor">
     <option value="Production Operator">
     <option value="Farm Laborer">
     <option value="Cook">
     <option value="Garbage Collector">
     <option value="Laundry Worker">
     <option value="Construction Laborer">
     <option value="Factory Worker">
     <option value="Gardener">
     <option value="Food Server">
     <option value="Caregiver">
     <option value="Street Sweeper">
     <option value="Pet Groomer">
     <option value="Messenger">
     <option value="Valet Parking Attendant">
     <option value="Babysitter">
     <option value="Painter">
     <option value="Farmhand">
     <option value="Dishwasher">
     <option value="Gasoline Attendant">
     <option value="Groundskeeper">
     <option value="Porter">
     <option value="Bar Helper">
     <option value="House Painter">
     <option value="Nanny">
     <option value="Parking Lot Attendant">
     <option value="Messenger">
     <option value="Bus Conductor">
     <option value="Dishwasher">
     <option value="Retail Merchandiser">
     <option value="Grocery Bagger">
     <option value="Day Laborer">
     <option value="Fruit Picker">
     <option value="Utility Worker">
     <option value="Car Washer">
     <option value="Gas Station Attendant">
     <option value="Messenger">
     <option value="Restaurant Server">
     <option value="Bank Teller">
     <option value="Barista">
     <option value="Bartender">
     <option value="Business Analyst">
     <option value="Cashier">
     <option value="Civil Engineer">
     <option value="Content Writer">
     <option value="Customer Service Representative">
     <option value="Data Analyst">
     <option value="Digital Marketing Specialist">
     <option value="Electrical Engineer">
     <option value="Graphic Designer">
     <option value="Human Resources Manager">
     <option value="IT Support Specialist">
     <option value="Java Developer">
     <option value="Legal Assistant">
     <option value="Marketing Manager">
     <option value="Medical Technologist">
     <option value="Nurse">
     <option value="Office Manager">
     <option value="Operations Manager">
     <option value="Pharmacist">
     <option value="Photographer">
     <option value="Product Manager">
     <option value="Project Manager">
     <option value="Receptionist">
     <option value="Registered Nurse">
     <option value="Sales Representative">
     <option value="Software Engineer">
     <option value="Teacher">
     <option value="Web Developer">
     <option value="Account Manager">
     <option value="Chef">
     <option value="Computer Programmer">
     <option value="Data Entry Clerk">
     <option value="Financial Analyst">
     <option value="Hotel Manager">
     <option value="Java Developer">
     <option value="Marketing Coordinator">
     <option value="Operations Coordinator">
     <option value="Physical Therapist">
     <option value="Product Manager">
     <option value="Public Relations Specialist">
     <option value="Sales Manager">
     <option value="Software Developer">
     <option value="Technical Support Specialist">
     <option value="Waiter/Waitress">
</datalist>

<datalist id="skill-list">
     <option value="Effective Communication">
     <option value="Adaptability">
     <option value="Customer Service">
     <option value="Teamwork">
     <option value="Time Management">
     <option value="Attention to Detail">
     <option value="Problem-Solving">
     <option value="Leadership">
     <option value="Critical Thinking">
     <option value="Creativity">
     <option value="Emotional Intelligence">
     <option value="Interpersonal Skills">
     <option value="Conflict Resolution">
     <option value="Empathy">
     <option value="Stress Management">
     <option value="Decision-Making">
     <option value="Negotiation">
     <option value="Active Listening">
     <option value="Organizational Skills">
     <option value="Flexibility">
     <option value="Initiative">
     <option value="Motivation">
     <option value="Positivity">
     <option value="Resilience">
     <option value="Self-Motivation">
     <option value="Work Ethic">
     <option value="Integrity">
     <option value="Cultural Sensitivity">
     <option value="Diplomacy">
     <option value="Adaptation to Change">
     <option value="Patience">
     <option value="Collaboration">
     <option value="Customer Relationship Management">
     <option value="Multitasking">
     <option value="Networking">
     <option value="Open-Mindedness">
     <option value="Tolerance">
     <option value="Time Management">
     <option value="Prioritization">
     <option value="Goal Setting">
     <option value="Delegation">
     <option value="Accountability">
     <option value="Conflict Management">
     <option value="Coaching">
     <option value="Presentation Skills">
     <option value="Problem Identification">
     <option value="Learning Agility">
     <option value="Decision-Making">
     <option value="Team Building">
     <option value="Self-Discipline">
     <option value="Web Development">
     <option value="Software Development">
     <option value="IT Support">
     <option value="Graphic Design">
     <option value="Multimedia Production">
     <option value="Mobile App Development">
     <option value="Database Administration">
     <option value="Network Administration">
     <option value="Systems Analysis">
     <option value="Quality Assurance Testing">
     <option value="Digital Marketing">
     <option value="SEO (Search Engine Optimization)">
     <option value="Content Writing">
     <option value="Database Management">
     <option value="Data Analysis">
     <option value="Project Management">
     <option value="Cybersecurity">
     <option value="Network Security">
     <option value="Software Quality Assurance">
     <option value="Data Science">
     <option value="Mobile Game Development">
     <option value="E-commerce Management">
     <option value="Hardware Troubleshooting">
     <option value="Cloud Computing">
     <option value="Electrical Engineering">
     <option value="Mechanical Engineering">
     <option value="Industrial Automation">
     <option value="Accounting">
     <option value="Financial Analysis">
     <option value="Marketing Analytics">
     <option value="Java Programming">
     <option value="C# Programming">
     <option value="Python Programming">
     <option value="Front-End Development">
     <option value="Back-End Development">
     <option value="UI/UX Design">
     <option value="Artificial Intelligence (AI)">
     <option value="Machine Learning">
     <option value="Robotics">
     <option value="3D Modeling">
     <option value="Video Editing">
     <option value="Audio Production">
     <option value="Health Care Management">
     <option value="Nursing">
     <option value="Medical Technology">
     <option value="Telecommunications">
     <option value="Environmental Science">
     <option value="Geographical Information Systems (GIS)">
     <option value="Civil Engineering">
     <option value="AutoCAD Design">
</datalist>

<datalist id="degree-list">
     <option value="Associate Degree (AA/AS)">
     <option value="Bachelor's Degree (BA/BS)">
     <option value="Master's Degree (MA/MS)">
     <option value="Doctoral Degree (Ph.D./Ed.D.)">
     <option value="Doctor of Medicine (MD)">
     <option value="Doctor of Dental Medicine (DMD) or Doctor of Dental Surgery (DDS)">
     <option value="Doctor of Jurisprudence (JD)">
     <option value="Doctor of Pharmacy (Pharm.D.)">
     <option value="Doctor of Veterinary Medicine (DVM)">
     <option value="Honorary Degrees">
     <option value="Online Degrees">
     <option value="Certificate/Diploma">
     <option value="Professional Degrees">
     <option value="Specialized Degrees">
</datalist>

<datalist id="field-study-list">
     <option value="Business and Management">
     <option value="Engineering">
     <option value="Education">
     <option value="Nursing and Healthcare">
     <option value="Information Technology (IT)">
     <option value="Tourism and Hospitality">
     <option value="Accounting and Finance">
     <option value="Criminology and Law Enforcement">
     <option value="Mass Communication and Journalism">
     <option value="Architecture and Design">
     <option value="Medical and Health Sciences">
     <option value="Environmental Science">
     <option value="Social Sciences">
     <option value="Agriculture and Agribusiness">
     <option value="Marine Biology and Fisheries">
     <option value="Computer Science">
     <option value="Psychology">
     <option value="Political Science">
     <option value="Civil Engineering">
     <option value="Pharmacy">
     <option value="Communication Arts">
     <option value="Electrical Engineering">
     <option value="Culinary Arts">
     <option value="Dentistry">
     <option value="Fine Arts">
     <option value="Mechanical Engineering">
     <option value="Hospitality Management">
     <option value="Economics">
     <option value="Chemical Engineering">
     <option value="Information Systems">
     <option value="Physical Therapy">
     <option value="Mathematics">
     <option value="Geology">
     <option value="Human Resource Management">
     <option value="Industrial Engineering">
     <option value="Marketing">
     <option value="Geography">
     <option value="Public Administration">
     <option value="Biological Sciences">
     <option value="Biomedical Engineering">
     <option value="Information Security">
     <option value="Speech Pathology">
     <option value="Biotechnology">
     <option value="Chemistry">
     <option value="Environmental Engineering">
     <option value="Data Science">
     <option value="Social Work">
     <option value="Library and Information Science">
     <option value="Applied Statistics">
     <option value="Aviation and Aeronautics">
     <option value="Archaeology">
     <option value="Tourism Management">
</datalist>

<datalist id="field-study-list">
     <option value="Business and Management">
     <option value="Engineering">
     <option value="Education">
     <option value="Nursing and Healthcare">
     <option value="Information Technology (IT)">
     <option value="Tourism and Hospitality">
     <option value="Accounting and Finance">
     <option value="Criminology and Law Enforcement">
     <option value="Mass Communication and Journalism">
     <option value="Architecture and Design">
     <option value="Medical and Health Sciences">
     <option value="Environmental Science">
     <option value="Social Sciences">
     <option value="Agriculture and Agribusiness">
     <option value="Marine Biology and Fisheries">
     <option value="Computer Science">
     <option value="Psychology">
     <option value="Political Science">
     <option value="Civil Engineering">
     <option value="Pharmacy">
     <option value="Communication Arts">
     <option value="Electrical Engineering">
     <option value="Culinary Arts">
     <option value="Dentistry">
     <option value="Fine Arts">
     <option value="Mechanical Engineering">
     <option value="Hospitality Management">
     <option value="Economics">
     <option value="Chemical Engineering">
     <option value="Information Systems">
     <option value="Physical Therapy">
     <option value="Mathematics">
     <option value="Geology">
     <option value="Human Resource Management">
     <option value="Industrial Engineering">
     <option value="Marketing">
     <option value="Geography">
     <option value="Public Administration">
     <option value="Biological Sciences">
     <option value="Biomedical Engineering">
     <option value="Information Security">
     <option value="Speech Pathology">
     <option value="Biotechnology">
     <option value="Chemistry">
     <option value="Environmental Engineering">
     <option value="Data Science">
     <option value="Social Work">
     <option value="Library and Information Science">
     <option value="Applied Statistics">
     <option value="Aviation and Aeronautics">
     <option value="Archaeology">
     <option value="Tourism Management">
</datalist>

<datalist id="company-sector">
     <option value="Information Technology">
     <option value="Healthcare">
     <option value="Finance">
     <option value="Retail">
     <option value="Manufacturing">
     <option value="Automotive">
     <option value="Energy">
     <option value="Education">
     <option value="Real Estate">
     <option value="Hospitality">
     <option value="Transportation">
     <option value="Telecommunications">
     <option value="Pharmaceuticals">
     <option value="Aerospace">
     <option value="Entertainment">
     <option value="Agriculture">
     <option value="Construction">
     <option value="Food and Beverage">
     <option value="Biotechnology">
     <option value="Media">
     <option value="E-commerce">
     <option value="Insurance">
     <option value="Banking">
     <option value="Fashion">
     <option value="Tourism">
     <option value="Environmental">
     <option value="Nonprofit">
     <option value="Mining">
     <option value="Legal">
     <option value="Government">
     <option value="Fitness">
     <option value="Gaming">
     <option value="Publishing">
     <option value="Music">
     <option value="Sports">
     <option value="Architecture">
     <option value="Art and Design">
     <option value="Software Development">
     <option value="Consulting">
     <option value="Marketing">
     <option value="Advertising">
     <option value="Renewable Energy">
     <option value="Internet Services">
     <option value="Pharmaceuticals">
     <option value="Health and Wellness">
     <option value="Consumer Electronics">
     <option value="Food Services">
     <option value="Chemicals">
     <option value="Printing">
     <option value="Forestry">
</datalist>

<datalist id="contact-position">
     <option value="CEO (Chief Executive Officer)">
     <option value="COO (Chief Operating Officer)">
     <option value="CFO (Chief Financial Officer)">
     <option value="CMO (Chief Marketing Officer)">
     <option value="CTO (Chief Technology Officer)">
     <option value="HR Manager (Human Resources Manager)">
     <option value="Sales Director">
     <option value="Marketing Manager">
     <option value="IT Manager (Information Technology Manager)">
     <option value="Project Manager">
     <option value="Account Manager">
     <option value="Product Manager">
     <option value="Business Development Manager">
     <option value="Operations Manager">
     <option value="Financial Analyst">
     <option value="Customer Service Representative">
     <option value="Data Analyst">
     <option value="Quality Assurance Specialist">
     <option value="Public Relations Manager">
     <option value="Graphic Designer">
     <option value="Legal Counsel">
     <option value="Research Scientist">
     <option value="Executive Assistant">
     <option value="Event Planner">
     <option value="Social Media Manager">
     <option value="Content Writer">
     <option value="Supply Chain Manager">
     <option value="Architect">
     <option value="Nurse Practitioner">
     <option value="Chef">
     <option value="Store Manager">
     <option value="Software Engineer">
     <option value="Investment Analyst">
     <option value="Teacher">
     <option value="Real Estate Agent">
     <option value="Electrician">
     <option value="Mechanic">
     <option value="Pharmacist">
     <option value="Librarian">
     <option value="Web Developer">
     <option value="Operations Coordinator">
     <option value="Customer Support Specialist">
     <option value="Art Director">
     <option value="Environmental Scientist">
     <option value="Financial Planner">
     <option value="Construction Supervisor">
     <option value="Marketing Coordinator">
     <option value="Technical Support Specialist">
     <option value="Physician Assistant">
     <option value="Research Analyst">
</datalist>

<datalist id="locations">
    <option value="Manila">
    <option value="Quezon City">
    <option value="Cebu City">
    <option value="Davao City">
    <option value="Makati">
    <option value="Pasig">
    <option value="Taguig">
    <option value="Pasay">
    <option value="Mandaluyong">
    <option value="Cagayan de Oro">
    <option value="Bacolod">
    <option value="Iloilo City">
    <option value="Angeles">
    <option value="Baguio">
    <option value="Bataan">
    <option value="Batangas City">
    <option value="Cabanatuan">
    <option value="Caloocan">
    <option value="Lapu-Lapu">
    <option value="Cavite City">
    <option value="San Fernando">
    <option value="General Santos">
    <option value="Lipa">
    <option value="Lucena">
    <option value="Naga">
    <option value="Olongapo">
    <option value="Roxas City">
    <option value="San Pablo">
    <option value="Tacloban">
    <option value="Zamboanga City">
    <option value="Cotabato">
    <option value="Dagupan">
    <option value="Tuguegarao">
    <option value="Dumaguete">
    <option value="General Trias">
    <option value="Iriga">
    <option value="Kabankalan">
    <option value="Kidapawan">
    <option value="Laoag">
    <option value="Mabalacat">
    <option value="Marawi">
    <option value="Navotas">
    <option value="Ormoc">
    <option value="Panabo">
    <option value="San Jose del Monte">
    <option value="Santiago">
    <option value="Tarlac City">
    <option value="Tayabas">
    <option value="Valenzuela">
</datalist>