-- Create backup tables for all original tables
CREATE TABLE `ADMIN_INFO_BACKUP` LIKE `ADMIN_INFO`;
CREATE TABLE `COMPANY_IMAGES_BACKUP` LIKE `COMPANY_IMAGES`;
CREATE TABLE `EMPLOYER_SIGNUP_INFO_BACKUP` LIKE `EMPLOYER_SIGNUP_INFO`;
CREATE TABLE `HIRED_NOTES_BACKUP` LIKE `HIRED_NOTES`;
CREATE TABLE `INTERVIEW_NOTES_BACKUP` LIKE `INTERVIEW_NOTES`;
CREATE TABLE `JOB_APPLICATION_STATUS_BACKUP` LIKE `JOB_APPLICATION_STATUS`;
CREATE TABLE `JOB_LISTING_BACKUP` LIKE `JOB_LISTING`;
CREATE TABLE `JOB_SEEKER_CAREER_HISTORY_BACKUP` LIKE `JOB_SEEKER_CAREER_HISTORY`;
CREATE TABLE `JOB_SEEKER_EDUCATION_INFO_BACKUP` LIKE `JOB_SEEKER_EDUCATION_INFO`;
CREATE TABLE `JOB_SEEKER_IMAGES_BACKUP` LIKE `JOB_SEEKER_IMAGES`;
CREATE TABLE `JOB_SEEKER_SIGNUP_INFO_BACKUP` LIKE `JOB_SEEKER_SIGNUP_INFO`;
CREATE TABLE `JOB_SEEKER_SKILL_BACKUP` LIKE `JOB_SEEKER_SKILL`;
CREATE TABLE `JOB_SEEKER_UPLOADED_RESUME_BACKUP` LIKE `JOB_SEEKER_UPLOADED_RESUME`;
CREATE TABLE `JOB_SEEKER_WORK_REVIEW_BACKUP` LIKE `JOB_SEEKER_WORK_REVIEW`;
CREATE TABLE `LOGIN_LOGS_BACKUP` LIKE `LOGIN_LOGS`;
CREATE TABLE `REQUEST_ACCOUNT_DELETION_BACKUP` LIKE `REQUEST_ACCOUNT_DELETION`;
CREATE TABLE `REQUEST_RESET_PASSWORD_BACKUP` LIKE `REQUEST_RESET_PASSWORD`;
CREATE TABLE `SAVED_JOB_LISTING_BACKUP` LIKE `SAVED_JOB_LISTING`;
CREATE TABLE `SimpleWords_BACKUP` LIKE `SimpleWords`;

DELIMITER //

CREATE TRIGGER `admin_info_backup_trigger` AFTER INSERT ON `ADMIN_INFO`
 FOR EACH ROW BEGIN
    INSERT INTO `ADMIN_INFO_BACKUP` SELECT * FROM `ADMIN_INFO` WHERE `admin_ID` = NEW.`admin_ID`;
END

CREATE TRIGGER `company_images_backup_trigger` AFTER INSERT ON `COMPANY_IMAGES`
 FOR EACH ROW BEGIN
    INSERT INTO `COMPANY_IMAGES_BACKUP` SELECT * FROM `COMPANY_IMAGES` WHERE `image_ID` = NEW.`image_ID`;
END

CREATE TRIGGER `employer_signup_info_backup_trigger` AFTER INSERT ON `EMPLOYER_SIGNUP_INFO`
 FOR EACH ROW BEGIN
    INSERT INTO `EMPLOYER_SIGNUP_INFO_BACKUP` SELECT * FROM `EMPLOYER_SIGNUP_INFO` WHERE `signup_ID` = NEW.`signup_ID`;
END

CREATE TRIGGER `hired_notes_backup_trigger` AFTER INSERT ON `HIRED_NOTES`
 FOR EACH ROW BEGIN
    INSERT INTO `HIRED_NOTES_BACKUP` SELECT * FROM `HIRED_NOTES` WHERE `noted_ID` = NEW.`noted_ID`;
END

CREATE TRIGGER `interview_notes_backup_trigger` AFTER INSERT ON `INTERVIEW_NOTES`
 FOR EACH ROW BEGIN
    INSERT INTO `INTERVIEW_NOTES_BACKUP` SELECT * FROM `INTERVIEW_NOTES` WHERE `note_ID` = NEW.`note_ID`;
END

CREATE TRIGGER `job_application_status_backup_trigger` AFTER INSERT ON `JOB_APPLICATION_STATUS`
 FOR EACH ROW BEGIN
    INSERT INTO `JOB_APPLICATION_STATUS_BACKUP` SELECT * FROM `JOB_APPLICATION_STATUS` WHERE `application_status_ID` = NEW.`application_status_ID`;
END

CREATE TRIGGER `job_listing_backup_trigger` AFTER INSERT ON `JOB_LISTING`
 FOR EACH ROW BEGIN
    INSERT INTO `JOB_LISTING_BACKUP` SELECT * FROM `JOB_LISTING` WHERE `job_id` = NEW.`job_id`;
END

CREATE TRIGGER `job_seeker_career_history_backup_trigger` AFTER INSERT ON `JOB_SEEKER_CAREER_HISTORY`
 FOR EACH ROW BEGIN
    INSERT INTO `JOB_SEEKER_CAREER_HISTORY_BACKUP` SELECT * FROM `JOB_SEEKER_CAREER_HISTORY` WHERE `career_history_ID` = NEW.`career_history_ID`;
END

CREATE TRIGGER `job_seeker_education_info_backup_trigger` AFTER INSERT ON `JOB_SEEKER_EDUCATION_INFO`
 FOR EACH ROW BEGIN
    INSERT INTO `JOB_SEEKER_EDUCATION_INFO_BACKUP` SELECT * FROM `JOB_SEEKER_EDUCATION_INFO` WHERE `education_info_ID` = NEW.`education_info_ID`;
END

CREATE TRIGGER `job_seeker_images_backup_trigger` AFTER INSERT ON `JOB_SEEKER_IMAGES`
 FOR EACH ROW BEGIN
    INSERT INTO `JOB_SEEKER_IMAGES_BACKUP` SELECT * FROM `JOB_SEEKER_IMAGES` WHERE `image_ID` = NEW.`image_ID`;
END

CREATE TRIGGER `job_seeker_signup_info_backup_trigger` AFTER INSERT ON `JOB_SEEKER_SIGNUP_INFO`
 FOR EACH ROW BEGIN
    INSERT INTO `JOB_SEEKER_SIGNUP_INFO_BACKUP` SELECT * FROM `JOB_SEEKER_SIGNUP_INFO` WHERE `signup_ID` = NEW.`signup_ID`;
END

CREATE TRIGGER `job_seeker_skill_backup_trigger` AFTER INSERT ON `JOB_SEEKER_SKILL`
 FOR EACH ROW BEGIN
    INSERT INTO `JOB_SEEKER_SKILL_BACKUP` SELECT * FROM `JOB_SEEKER_SKILL` WHERE `skill_ID` = NEW.`skill_ID`;
END

CREATE TRIGGER `job_seeker_uploaded_resume_backup_trigger` AFTER INSERT ON `JOB_SEEKER_UPLOADED_RESUME`
 FOR EACH ROW BEGIN
    INSERT INTO `JOB_SEEKER_UPLOADED_RESUME_BACKUP` SELECT * FROM `JOB_SEEKER_UPLOADED_RESUME` WHERE `resume_ID` = NEW.`resume_ID`;
END

CREATE TRIGGER `job_seeker_work_review_backup_trigger` AFTER INSERT ON `JOB_SEEKER_WORK_REVIEW`
 FOR EACH ROW BEGIN
    INSERT INTO `JOB_SEEKER_WORK_REVIEW_BACKUP` SELECT * FROM `JOB_SEEKER_WORK_REVIEW` WHERE `work_review_ID` = NEW.`work_review_ID`;
END

CREATE TRIGGER `login_logs_backup_trigger` AFTER INSERT ON `LOGIN_LOGS`
 FOR EACH ROW BEGIN
    INSERT INTO `LOGIN_LOGS_BACKUP` SELECT * FROM `LOGIN_LOGS` WHERE `login_log_ID` = NEW.`login_log_ID`;
END

CREATE TRIGGER `request_account_deletion_backup_trigger` AFTER INSERT ON `REQUEST_ACCOUNT_DELETION`
 FOR EACH ROW BEGIN
    INSERT INTO `REQUEST_ACCOUNT_DELETION_BACKUP` SELECT * FROM `REQUEST_ACCOUNT_DELETION` WHERE `request_deletion_id` = NEW.`request_deletion_id`;
END

CREATE TRIGGER `request_reset_password_backup_trigger` AFTER INSERT ON `REQUEST_RESET_PASSWORD`
 FOR EACH ROW BEGIN
    INSERT INTO `REQUEST_RESET_PASSWORD_BACKUP` SELECT * FROM `REQUEST_RESET_PASSWORD` WHERE `request_password_id` = NEW.`request_password_id`;
END

CREATE TRIGGER `saved_job_listing_backup_trigger` AFTER INSERT ON `SAVED_JOB_LISTING`
 FOR EACH ROW BEGIN
    INSERT INTO `SAVED_JOB_LISTING_BACKUP` SELECT * FROM `SAVED_JOB_LISTING` WHERE `saved_id` = NEW.`saved_id`;
END

CREATE TRIGGER `simple_words_backup_trigger` AFTER INSERT ON `SimpleWords`
 FOR EACH ROW BEGIN
    INSERT INTO `SimpleWords_BACKUP` SELECT * FROM `SimpleWords` WHERE `id` = NEW.`id`;
END

DELIMITER ;
